id: PBDBA4D24
initial_creation_type: ocr
source_metadata:
  volumes:
    efc1af87e8e4434792630ac34f855871:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: དབྱུག་པ་གཤིན་རྗེ་གཤེད་རྣམ་པར་འཇོམས་པ་ཞེས་བྱ་བའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
